#source 'https://github.com/Carota-MarketPlanner/podspecs.git'
source 'git@github.com:Carota-MarketPlanner/Specs.git'

platform :ios, '15.0'
use_frameworks!

target 'CDSComponents_Example' do
  pod 'CDSComponents/Source', :path => '../'
  
  pod 'CarotaTheme/Source', '1.0.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 15.0
      end
    end
  end
end
