name: Build And Publish Production

on:
  push:
    branches: [ "main" ]

permissions:
      contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  create-tag:
    name: Creates Tag
    uses: ./.github/workflows/publish-tag.yml
    with: 
      name: ${{ needs.build.outputs.name }}
      version: ${{ needs.build.outputs.version }}
    needs: [build]
    secrets: inherit

  publish:
    name: Publish Production
    uses: ./.github/workflows/publish-github-production.yml
    with: 
      name: ${{ needs.create-tag.outputs.name }}
      version: ${{ needs.create-tag.outputs.version }}
    needs: [create-tag]
    secrets: inherit

  update-podspec:
    name: Update Podspec With Production
    uses: ./.github/workflows/update-podspecs-production.yml
    with: 
      name: ${{ needs.publish.outputs.name }}
      version: ${{ needs.publish.outputs.version }}
    needs: [publish]
    secrets: inherit
    