name: Publish Production on GitHub

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string

    outputs:
      name:
        description: "Pod Name"
        value: ${{ inputs.name }}
      version: 
        description: "Pod Version"
        value: ${{ inputs.version }}
      
jobs:
  publish:
    name: Publish GitHub Release Production
    runs-on: macos-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Downloading XCFramework
        uses: actions/download-artifact@v4
        with:
          name: xcframework-${{ inputs.name }}-${{ inputs.version }}
          path: ${{ inputs.name }}.xcframework

      - name: Compacting XCFramework
        run: |
          mkdir -p compacted
          zip -r compacted/${{ inputs.name }}-${{ inputs.version }}.zip ${{ inputs.name }}.xcframework

      - name: Criating GitHub Production Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          files: compacted/*
          body: |
            Release automática da versão ${{ inputs.version }} for production
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
