name: Create New TAG on GitHub

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string

    outputs:
      name:
        description: "Pod Name"
        value: ${{ inputs.name }}
      version: 
        description: "Pod Version"
        value: ${{ inputs.version }}
      
jobs:
  publish:
    name: Creates New Tag from Version
    runs-on: macos-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Criating tag and pushing
        run: |
          TAG=${{ inputs.version }}

          # verifica se a tag já existe
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
            echo "Tag $TAG already exists | Can't be overwritten!"
            exit 1  # Se quiser impedir o próximo step, falhe aqui!
          else
            git tag $TAG
            git push origin $TAG
          fi
